[book]
authors = ["Pablo Ovelleiro Corral"]
language = "de"
multilingual = false
src = "src"
title = "Kitchen's Datasheet"


[preprocessor.cmdrun]

# [preprocessor.headtable]
# command = "python headtable.py"


# [preprocessor.nutrition]
# command = "python headtable.py"

[output.html]
theme = "theme"
default-theme = "light"
preferred-dark-theme = "light"
git-repository-url = "https://github.com/pinpox/kitchen-datasheet"
